version: '3'
services:
  api_chtuka:
    build:
      dockerfile: Dockerfile
    ports:
      - "81:81"
    environment:
      DB_HOST: db_chtuka
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db_chtuka
      - redis-chtuka
    networks:
      - app-network-chtuka

  db_chtuka:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
        - app-network-chtuka

  redis-chtuka:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app-network-chtuka

networks:
  app-network-chtuka:
    driver: bridge
  shared-network:
    external: true
