version: '3'
services:

  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_NAME: postgres

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
