version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    depends_on:
      - api

  api:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_NAME: postgres

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
