version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - app-network-api

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - app-network-api

  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    networks:
      - app-network-api

networks:
  app-network-api:
    driver: bridge
  shared-network:
    external: true
