/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceSchema
 */
export interface DeviceSchema {
    /**
     * 
     * @type {string}
     * @memberof DeviceSchema
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceSchema
     */
    descr: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DeviceSchema
     */
    name?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DeviceSchema interface.
 */
export function instanceOfDeviceSchema(value: object): value is DeviceSchema {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('descr' in value) || value['descr'] === undefined) return false;
    return true;
}

export function DeviceSchemaFromJSON(json: any): DeviceSchema {
    return DeviceSchemaFromJSONTyped(json, false);
}

export function DeviceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'],
        'descr': json['descr'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DeviceSchemaToJSON(value?: DeviceSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'externalId': value['externalId'],
        'descr': value['descr'],
        'name': value['name'],
    };
}

