/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureProductSchema
 */
export interface FeatureProductSchema {
    /**
     * 
     * @type {string}
     * @memberof FeatureProductSchema
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProductSchema
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProductSchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FeatureProductSchema
     */
    quota: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureProductSchema
     */
    validPeriod: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FeatureProductSchema
     */
    title?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FeatureProductSchema
     */
    descr?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FeatureProductSchema
     */
    custom?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FeatureProductSchema
     */
    prices?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<{ [key: string]: string; }>}
     * @memberof FeatureProductSchema
     */
    image?: Array<{ [key: string]: string; }> | null;
}

/**
 * Check if a given object implements the FeatureProductSchema interface.
 */
export function instanceOfFeatureProductSchema(value: object): value is FeatureProductSchema {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quota' in value) || value['quota'] === undefined) return false;
    if (!('validPeriod' in value) || value['validPeriod'] === undefined) return false;
    return true;
}

export function FeatureProductSchemaFromJSON(json: any): FeatureProductSchema {
    return FeatureProductSchemaFromJSONTyped(json, false);
}

export function FeatureProductSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureProductSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'],
        'status': json['status'],
        'name': json['name'],
        'quota': json['quota'],
        'validPeriod': json['validPeriod'],
        'title': json['title'] == null ? undefined : json['title'],
        'descr': json['descr'] == null ? undefined : json['descr'],
        'custom': json['custom'] == null ? undefined : json['custom'],
        'prices': json['prices'] == null ? undefined : json['prices'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function FeatureProductSchemaToJSON(value?: FeatureProductSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'externalId': value['externalId'],
        'status': value['status'],
        'name': value['name'],
        'quota': value['quota'],
        'validPeriod': value['validPeriod'],
        'title': value['title'],
        'descr': value['descr'],
        'custom': value['custom'],
        'prices': value['prices'],
        'image': value['image'],
    };
}

