/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupProductSchema
 */
export interface GroupProductSchema {
    /**
     * 
     * @type {string}
     * @memberof GroupProductSchema
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof GroupProductSchema
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof GroupProductSchema
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GroupProductSchema
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GroupProductSchema
     */
    title?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GroupProductSchema
     */
    descr?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GroupProductSchema
     */
    custom?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GroupProductSchema
     */
    prices?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<{ [key: string]: string; }>}
     * @memberof GroupProductSchema
     */
    image?: Array<{ [key: string]: string; }> | null;
}

/**
 * Check if a given object implements the GroupProductSchema interface.
 */
export function instanceOfGroupProductSchema(value: object): value is GroupProductSchema {
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupProductSchemaFromJSON(json: any): GroupProductSchema {
    return GroupProductSchemaFromJSONTyped(json, false);
}

export function GroupProductSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupProductSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'],
        'type': json['type'],
        'status': json['status'],
        'name': json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'descr': json['descr'] == null ? undefined : json['descr'],
        'custom': json['custom'] == null ? undefined : json['custom'],
        'prices': json['prices'] == null ? undefined : json['prices'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function GroupProductSchemaToJSON(value?: GroupProductSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'externalId': value['externalId'],
        'type': value['type'],
        'status': value['status'],
        'name': value['name'],
        'title': value['title'],
        'descr': value['descr'],
        'custom': value['custom'],
        'prices': value['prices'],
        'image': value['image'],
    };
}

