/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSchema
 */
export interface ProductSchema {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ProductSchema
     */
    title?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ProductSchema interface.
 */
export function instanceOfProductSchema(value: object): value is ProductSchema {
    return true;
}

export function ProductSchemaFromJSON(json: any): ProductSchema {
    return ProductSchemaFromJSONTyped(json, false);
}

export function ProductSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ProductSchemaToJSON(value?: ProductSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
    };
}

