/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileSchema
 */
export interface ProfileSchema {
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSchema
     */
    descr: string;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    age: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    pin: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileSchema
     */
    purchasePin: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ProfileSchema
     */
    custom?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<{ [key: string]: string; }>}
     * @memberof ProfileSchema
     */
    image?: Array<{ [key: string]: string; }> | null;
}

/**
 * Check if a given object implements the ProfileSchema interface.
 */
export function instanceOfProfileSchema(value: object): value is ProfileSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('descr' in value) || value['descr'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('purchasePin' in value) || value['purchasePin'] === undefined) return false;
    return true;
}

export function ProfileSchemaFromJSON(json: any): ProfileSchema {
    return ProfileSchemaFromJSONTyped(json, false);
}

export function ProfileSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'descr': json['descr'],
        'age': json['age'],
        'pin': json['pin'],
        'purchasePin': json['purchasePin'],
        'custom': json['custom'] == null ? undefined : json['custom'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ProfileSchemaToJSON(value?: ProfileSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'descr': value['descr'],
        'age': value['age'],
        'pin': value['pin'],
        'purchasePin': value['purchasePin'],
        'custom': value['custom'],
        'image': value['image'],
    };
}

