/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a very cool project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGroupProductServicesRequest
 */
export interface SetGroupProductServicesRequest {
    /**
     * 
     * @type {number}
     * @memberof SetGroupProductServicesRequest
     */
    groupProductId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetGroupProductServicesRequest
     */
    serviceIds: Array<number>;
}

/**
 * Check if a given object implements the SetGroupProductServicesRequest interface.
 */
export function instanceOfSetGroupProductServicesRequest(value: object): value is SetGroupProductServicesRequest {
    if (!('groupProductId' in value) || value['groupProductId'] === undefined) return false;
    if (!('serviceIds' in value) || value['serviceIds'] === undefined) return false;
    return true;
}

export function SetGroupProductServicesRequestFromJSON(json: any): SetGroupProductServicesRequest {
    return SetGroupProductServicesRequestFromJSONTyped(json, false);
}

export function SetGroupProductServicesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGroupProductServicesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'groupProductId': json['groupProductId'],
        'serviceIds': json['serviceIds'],
    };
}

export function SetGroupProductServicesRequestToJSON(value?: SetGroupProductServicesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupProductId': value['groupProductId'],
        'serviceIds': value['serviceIds'],
    };
}

